- name: Arch Install and Configure
  hosts: localhost
  tasks:
    - name: Set the time zone
      file:
        path: /etc/localtime
        src: /usr/share/zoneinfo/Europe/London
        state: link

    - name: Run hwclock
      command:
        cmd: hwclock --systohc
        creates: /etc/adjtime

    - name: Prepare locales
      lineinfile:
        path: /etc/locale.gen
        line: "{{ item }}"
        search_string: "#{{ item }}"
      loop:
        - "LANG=en_US.UTF-8"
        - "LANG=en_GB.UTF-8"

    - name: Generate locales
      command: locale-gen
      changed_when: true

    - name: Create locale conf
      copy:
        content: |
          LANG=en_GB.UTF-8
        dest: /etc/locale.conf
        owner: root
        mode: '0644'

    - name: Create console keymap conf
      copy:
        content: |
          KEYMAP=uk
        dest: /etc/vconsole.conf
        owner: root
        mode: '0644'

    - name: Create hostname conf
      copy:
        content: |
          andrew-desktop
        dest: /etc/hostname
        owner: root
        mode: '0644'

    - name: Add mkinitcpio hooks
      tags: initramfs
      lineinfile:
        line: "HOOKS=({{ hooks | join(' ') }})"
        regexp: '^HOOKS=\(.+\)'
        path: /etc/mkinitcpio.conf
      vars:
        hooks:
          - base
          - systemd
          - keyboard
          - autodetect
          - modconf
          - kms
          - block
          - sd-vconsole
          - sd-encrypt
          - lvm2
          - filesystems
          - fsck

    - name: Generate initramfs
      tags: initramfs
      command: mkinitcpio -P
      changed_when: true

    - name: Install grub and microcode packages
      community.general.pacman:
        name:
          - efibootmgr
          - grub
          - intel-ucode

    - name: Install grub
      command: grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB
      changed_when: true

    - name: Configure grub
      lineinfile:
        path: /etc/default/grub
        regexp: "^GRUB_CMDLINE_LINUX=\".+\""
        line: "GRUB_CMDLINE_LINUX=\"{{ params | join(' ') }}\""
      vars:
        device: nvme0n1
        uuid: "{{ ansible_facts['devices'][device]['partitions'][device + 'p2']['uuid'] }}"
        params:
          - "rd.luks.name={{ uuid }}=cryptlvm root=/dev/MyVolGroup/root"
          - "nvidia.modeset=1"
      changed_when: true

    - name: Generate grub config
      command: grub-mkconfig -o /boot/grub/grub.cfg
      changed_when: true
