- name: apply configuration
  hosts: localhost
  vars:
    home: "/home/{{ user_name }}"
  roles:
    - role: base
      tags: base
    - role: home
      tags: home
    - role: bluetooth
      tags: bluetooth
    - role: developer
      tags: developer
    - role: desktop
      tags: desktop

    - nvidia

