- name: Apply configuration
  hosts: system
  vars:
    home: "/home/{{ user_name }}"
  roles:
    - role: base
      tags: base
    - role: home
      tags: home
    - role: bluetooth
      tags: bluetooth
    - role: developer
      become: true
      tags: developer
    - role: desktop
      become: true
      tags: desktop

    - role: nvidia
