---
- name: Install desktop packages
  community.general.pacman:
    name:
      - avahi
      - cups
      - cups-pdf
      - dosfstools
      - firefox-developer-edition
      - gnome
      - gnome-extra
      - nss-mdns
      - ntfs-3g
      - texlive
      - wl-clipboard
    state: present

- name: Enable gdm
  service:
    name: gdm
    enabled: true

- name: Configure local hostname service
  lineinfile:
    path: /etc/nsswitch.conf
    regex: '^hosts: .+'
    line: 'hosts: mymachines mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] files myhostname dns'
    state: present

- name: Enable mdns service
  service:
    name: avahi-daemon
    enabled: true

- name: Enable .xmlprinting service
  service:
    name: cups
    enabled: true

- name: Create temporary directory
  tempfile:
    state: directory
    suffix: ansible
  register: tempdir

- name: Set tempdir permissions
  file:
    path: "{{ tempdir.path }}"
    mode: "0755"
  register: tempdir

- name: Download desktop backgrounds
  get_url:
    url: "{{ item.url }}"
    dest: "{{ tempdir.path }}/{{ item.dest }}"
    mode: "0644"
  loop: "{{ desktop_wallpapers }}"

- name: Process desktop backgrounds
  command: >
    magick
    "{{ tempdir.path }}/{{ item.dest }}"
    -resize {{ item.width }}x
    "/usr/share/backgrounds/{{ item.dest | splitext | first }}.jpg"
  loop: "{{ desktop_wallpapers }}"
  changed_when: true

- name: Copy desktop backgrounds config
  template:
    src: wallpapers.xml.j2
    dest: /usr/share/gnome-background-properties/wallpapers.xml
    owner: root
    mode: '0644'

- name: Install microsoft fonts
  become: false
  import_tasks: aur.yml
  vars:
    aur_repository: "https://aur.archlinux.org/ttf-segoe-ui-variable"

- name: Install autofs
  become: true
  import_tasks: aur.yml
  vars:
    aur_repository: "https://aur.archlinux.org/autofs.git"

- name: Enable autofs service
  service:
    name: autofs
    enabled: true
