---
  - name: install desktop packages
    become: true
    pacman:
      name:
        - avahi
        - cups
        - cups-pdf
        - dosfstools
        - exfat-progs
        - gnome
        - gnome-extra
        - nss-mdns
        - ntfs-3g
        - texlive
        - wl-clipboard
      state: present

  - name: enable gdm
    become: true
    service:
      name: gdm
      enabled: yes
      state: started

  - name: configure local hostname service
    become: true
    lineinfile:
      path: /etc/nsswitch.conf
      regex: '^hosts:'
      line: 'hosts: mymachines mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] files myhostname dns'
      state: present

  - name: enable mdns service
    become: true
    service:
      name: avahi-daemon
      enabled: yes
      state: started

  - name: enable printing service
    become: true
    service:
      name: cups
      enabled: yes
      status: started
