---
  - name: install desktop packages
    pacman:
      name:
        - avahi
        - cups
        - cups-pdf
        - dosfstools
        - exfat-utils
        - firefox-developer-edition
        - gnome
        - gnome-extra
        - nss-mdns
        - ntfs-3g
        - texlive
        - wl-clipboard
      state: present

  - name: enable gdm
    service:
      name: gdm
      enabled: yes

  - name: configure local hostname service
    lineinfile:
      path: /etc/nsswitch.conf
      regex: '^hosts: .+'
      line: 'hosts: mymachines mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] files myhostname dns'
      state: present

  - name: enable mdns service
    service:
      name: avahi-daemon
      enabled: yes

  - name: enable printing service
    service:
      name: cups
      enabled: yes

