---
  - name: install desktop packages
    pacman:
      name:
        - avahi
        - cups
        - cups-pdf
        - dosfstools
        - firefox-developer-edition
        - gnome
        - gnome-extra
        - nss-mdns
        - ntfs-3g
        - texlive
        - wl-clipboard
      state: present

  - name: enable gdm
    service:
      name: gdm
      enabled: yes

  - name: configure local hostname service
    lineinfile:
      path: /etc/nsswitch.conf
      regex: '^hosts: .+'
      line: 'hosts: mymachines mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] files myhostname dns'
      state: present

  - name: enable mdns service
    service:
      name: avahi-daemon
      enabled: yes

  - name: enable .xmlprinting service
    service:
      name: cups
      enabled: yes

  - name: create temporary directory
    tempfile:
      state: directory
      suffix: ansible
    register: tempdir

  - name: set tempdir permissions
    file:
      path: "{{ tempdir.path }}"
      mode: "0755"
    register: tempdir

  - name: download desktop backgrounds
    get_url:
      url: "{{ item.url }}"
      dest: "{{ tempdir.path }}/{{ item.dest }}"
      mode: "0644"
    loop: "{{ wallpapers }}"

  - name: process desktop backgrounds
    shell: >
      magick
      "{{ tempdir.path }}/{{ item.dest }}"
      -resize {{ item.width}}x 
      "/usr/share/backgrounds/{{ item.dest | splitext | first }}.jpg"
    loop: "{{ wallpapers }}"

  - name: copy desktop backgrounds config
    template:
      src: wallpapers.xml.j2
      dest: /usr/share/gnome-background-properties/wallpapers.xml
