---
  - name: install bluetooth packages
    become: true
    pacman:
      name:
        - openssh
        - bluez
        - bluez-utils
      state: present

  - name: enable bluetooth service
    become: true
    service:
      name: bluetooth
      enabled: true
      state: started
