---
- name: Remove default nvidia driver
  become: true
  community.general.pacman:
    name:
      - nvidia
    state: absent

- name: Install nvidia dkms driver
  become: true
  community.general.pacman:
    name:
      - linux-headers
      - nvidia-open-dkms
    state: present

- name: Install nvidia module config
  become: true
  copy:
    src: nvidia.conf
    dest: /etc/modprobe.d/
    owner: root
    mode: '0644'

- name: Blacklist nouveau
  become: true
  copy:
    src: blacklist_nouveau.conf
    dest: /etc/modprobe.d/
    owner: root
    mode: '0644'

- name: Install cuda packages
  become: true
  community.general.pacman:
    name:
      - cuda
      - nvidia-container-toolkit
    state: present

- name: Enable nvidia-suspend service
  become: true
  service:
    name: nvidia-suspend
    enabled: true
    state: started

- name: Enable nvidia-resume service
  become: true
  service:
    name: nvidia-resume
    enabled: true
    state: started
