---
  - name: remove default nvidia driver
    become: true
    pacman:
      name:
        - nvidia
      state: absent

  - name: install nvidia dkms driver
    become: true
    pacman:
      name:
        - linux-lts-headers
        - nvidia-dkms
      state: present

  - name: install nvidia module config
    become: true
    copy:
      src: nvidia.conf
      dest: /etc/modprobe.d/

  - name: blacklist nouveau
    become: true
    copy:
      src: blacklist_nouveau.conf
      dest: /etc/modprobe.d/

  - name: install cuda packages
    become: true
    pacman:
      name:
        - cuda
      state: present

  - name: enable nvidia-suspend service
    become: true
    service:
      name: nvidia-suspend
      enabled: true
      state: started

  - name: enable nvidia-resume service
    become: true
    service:
      name: nvidia-resume
      enabled: true
      state: started
