---
- name: create user
  user:
    name: '{{ user_name }}'
    comment: '{{ full_name }}'
    password: '{{ password }}'
    create_home: true
    skeleton: /etc/skel
    groups: wheel
    ssh_key_file: .ssh/id_ed25519
    ssh_key_type: ed25519

- name: copy bashrc
  copy:
    src: bashrc
    dest: '{{ home }}/.bashrc'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: '0640'

- name: create projects folder
  file:
    path: /home/{{ user_name }}/projects
    state: directory
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: '0750'

- name: setup git config
  git_config:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
  loop:
    - { name: user.name, value: '{{ git_user_name }}' }
    - { name: user.email, value: '{{ user_email }}' }

- name: install liquidprompt
  git:
    repo: 'https://github.com/nojhan/liquidprompt.git'
    version: stable
    dest: '{{ home }}/.liquidprompt'

- name: set ownership on liquidprompt
  file:
    path: '{{ home }}/.liquidprompt'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    state: directory
    recurse: true

- name: install sudo package
  become: true
  pacman:
    name:
    - sudo
    state: present

- name: enable sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    search_string: '# %wheel ALL=(ALL:ALL) ALL'
    line: '%wheel ALL=(ALL:ALL) ALL'
    state: present
    validate: visudo -cf %s
  become: true
