---
- name: create user
  user:
    name: '{{ user_name }}'
    create_home: true
    skeleton: /etc/skel
    groups: wheel
    ssh_key_file: .ssh/id_ed25519
    ssh_key_type: ed25519

- name: copy bashrc
  copy:
    src: bashrc
    dest: /home/{{ user_name }}/.bashrc
    owner: '{{ user_name }}'
    mode: '0644'

- name: create projects folder
  file:
    /home/{{ user_name }}/projects

- name: setup git config
  git_config:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
  loop:
    - { name: user.name, value: '{{ git_user_name }}' }
    - { name: user.email, value: '{{ user_email }}' }

