---
- name: Create user
  tags: user
  user:
    name: '{{ user_name }}'
    comment: '{{ full_name }}'
    password: '{{ password }}'
    create_home: true
    skeleton: /etc/skel
    groups: wheel
    generate_ssh_key: true
    ssh_key_file: .ssh/id_ed25519
    ssh_key_type: ed25519
    state: present

- name: Copy bashrc and friends
  copy:
    src: "{{ item }}"
    dest: '{{ home }}/.{{ item }}'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: '0640'
  loop:
    - bashrc
    - bash_profile
    - profile

- name: Create projects folder
  file:
    path: /home/{{ user_name }}/projects
    state: directory
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: '0750'

- name: Setup git config
  community.general.git_config:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
  loop:
    - { name: user.name, value: '{{ git_user_name }}' }
    - { name: user.email, value: '{{ user_email }}' }

- name: Install liquidprompt
  git:
    repo: 'https://github.com/nojhan/liquidprompt.git'
    version: stable
    dest: '{{ home }}/.liquidprompt'

- name: Set ownership on liquidprompt
  file:
    path: '{{ home }}/.liquidprompt'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    state: directory
    recurse: true
