---
- name: install base packages
  become: true
  pacman:
    name:
    - git
    - inetutils
    - pacman-contrib
    - pwgen
    - sudo
    - unzip
    - wget
    update_cache: true
    state: present

- name: enable sudo
  become: true
  lineinfile:
    dest: /etc/sudoers
    search_string: '# %wheel ALL=(ALL:ALL) ALL'
    line: '%wheel ALL=(ALL:ALL) ALL'
    state: present
    validate: visudo -cf %s

- name: start paccache clear service
  become: true
  service:
    name: paccache.timer
    state: started
    enabled: true

- name: disable the terminal beep
  become: true
  copy:
    src: disable_beep.conf
    dest: /etc/profile.d
