---
- name: install base packages
  become: true
  pacman:
    name:
    - git
    - inetutils
    - sudo
    - unzip
    - wget
    update_cache: true
    state: present

- name: get yay from git
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: /tmp/yay

- name: install yay
  command:
    chdir: /tmp/yay
    cmd: makepkg --clean --install --rmdeps --syncdeps --noconfirm

- name: enable sudo
  lineinfile:
    dest: /etc/sudoers
    search_string: '# %wheel ALL=(ALL:ALL) ALL'
    line: '%wheel ALL=(ALL:ALL) ALL'
    state: present
    validate: visudo -cf %s
  become: true
