---
- name: Install base packages
  become: true
  community.general.pacman:
    name:
      - git
      - inetutils
      - pacman-contrib
      - pwgen
      - reflector
      - sudo
      - unzip
      - wget
    update_cache: true
    state: present

- name: Enable sudo
  become: true
  lineinfile:
    dest: /etc/sudoers
    search_string: '# %wheel ALL=(ALL:ALL) ALL'
    line: '%wheel ALL=(ALL:ALL) ALL'
    state: present
    validate: visudo -cf %s

- name: Start paccache clear service
  become: true
  service:
    name: paccache.timer
    state: started
    enabled: true

- name: Start the reflector service
  become: true
  service:
    name: reflector
    state: started
    enabled: true

- name: Disable the terminal beep
  become: true
  copy:
    src: disable_beep.conf
    dest: /etc/profile.d
    owner: root
    mode: '0644'
