---
- name: install base packages
  become: true
  pacman:
    name:
    - inetutils
    - sudo
    - unzip
    - wget
    state: present

- name: enable sudo
  lineinfile:
    dest: /etc/sudoers
    search_string: '# %wheel ALL=(ALL:ALL) ALL'
    line: '%wheel ALL=(ALL:ALL) ALL'
    state: present
    validate: visudo -cf %s
  become: true
