name: Ansible Linux

on: [push]

jobs:
  lint:
    name: static-analysis

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
